---
- set_fact:
    awx_dt_access_token_id: "{{ dt_api_token_ids[awx_dt_access_token_name] }}"
  ignore_errors: true

- include_role:
    name: dt-access-token
    tasks_from: delete
  vars:
    dynatrace_api_token_id: "{{ awx_dt_access_token_id }}"
  when: awx_dt_access_token_id is defined
